spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SeafoodStoreDB;encrypt=false
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false
spring.servlet.multipart.max-file-size=10MB
server.servlet.session.timeout=30m

# Encoding Settings to fix Vietnamese mojibake
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
spring.thymeleaf.encoding=UTF-8
spring.messages.encoding=UTF-8

# Tam thoi tat Spring Security de debug nhanh, bo dong nay de bat lai.

# Gemini AI Configuration
gemini.api.key=${GEMINI_API_KEY:AIzaSyCNQSY1u90smW5HywhURdWLUUMI-s_Gjf8}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

payos.apiKey=${PAYOS_API_KEY:bbcc1116-e138-4f89-b7b9-7d1c4ff95cfc}
payos.checksumKey=${PAYOS_CHECKSUM_KEY:11b9114e65bf0e9bc2c0041abdeca78066d887b5461f125fa58e443ef5790f18}
payos.clientId=${PAYOS_CLIENT_ID:c85a4c20-70c7-42d8-9f95-30d9331ebb90}

cloudinary.cloud_name=${CLOUD_NAME:de0xc35ew}
cloudinary.api_key=${API_KEY:147126675222571}
cloudinary.api_secret=${API_SECRET:rWraViCzS8k71FHQKmpEV4a1SMc}
